import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
        suppressHydrationWarning
      >
        <div className="opacity-40 -z-50 pointer-events-none">
          <Image src="/background2.jpg" fill alt="" className="object-cover" />
        </div>
        {children}
      </body>
    </html>
  );
}
